#!/usr/bin/env bash
# Display formatted information from /etc/passwd

while IFS=: read -r username password userid groupid info home shell; do
    echo "The user $username is part of the $groupid gang, lives in $home and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $userid $info"
done < /etc/passwd
