#!/usr/bin/env bash
# This script is displaying "bad luck" at the 4th iteration
# This script displays "Good luck" at the 8th iteration
# It also displays Best School otherwise

counter=1
while [ $counter -le 10 ]
do
	if [ $counter -eq 4 ]
	then
		echo "bad luck"
	elif [ $counter -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
